PanelGestorDeHorarios/Controllers/LogoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using System.IO;
using System.Threading.Tasks;

namespace TuProyecto.Controllers
{
    public class LogoController : Controller
    {
        public IActionResult UploadLogo()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile imageFile)
        {
            if (imageFile != null && imageFile.Length > 0)
            {
                // Guardar la imagen en el servidor
                var imagePath = Path.Combine("wwwroot", "logo.png");
                using (var stream = new FileStream(imagePath, FileMode.Create))
                {
                    await imageFile.CopyToAsync(stream);
                }

                // Redirigir o realizar alguna otra acción después de la carga exitosa
                return RedirectToAction("Index", "Home");
            }
            else
            {
                // Manejar el caso en que no se seleccionó ningún archivo
                ModelState.AddModelError("", "Por favor selecciona una imagen.");
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

PanelGestorDeHorarios/Controllers/SuperadministradorController.cs
using Microsoft.AspNetCore.Mvc;
using PanelGestorDeHorarios.Models;
using System.Diagnostics;

namespace PanelGestorDeHorarios.Controllers
{
    public class SuperadministradorController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public SuperadministradorController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PersonalizarPagina()
        {
            return View();
        }

        public IActionResult Soporte()
        {
            return View();
        }

        public IActionResult PanelSuperadministrador()
        {
            return View();
        }
    }
}

PanelGestorDeHorarios/Views/Superadministrador/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center vista-superadministrador-titulo m-auto">
    <h1 class="display-5 fw-bold">¡Bienvenido, super administrador, al Instituto Tecnológico de Mérida!</h1>
</div>

<div class="reloj display-6">
    <div class="hora" id="hora"></div>
    <div>:</div>
    <div class="minutos" id="minutos"></div>
</div>

<div class="row">
    <div class="col-md-7">
        <br />
        <div><span class="h3 fw-bold">Ciclo escolar vigente: &nbsp</span><span class="h3">2024 - 2025</span></div>
        <br />
        <div><span class="h3 fw-bold">Total de profesores registrados: &nbsp</span><span class="h3">6</span></div>
        <br />
        <div><span class="h3 fw-bold">Total de materias registradas: &nbsp</span><span class="h3">17</span></div>
        <br />
        <div><span class="h3 fw-bold">Aulas totales: &nbsp</span><span class="h3">20</span></div>

        <br />
        <div class="d-flex justify-content-center">
            <div class="calendario">
                <div class="mes">
                    <div class="titulo">Marzo 2024</div>
                </div>
                <div class="dias-semana">
                    <div class="dia">Lun</div>
                    <div class="dia">Mar</div>
                    <div class="dia">Mié</div>
                    <div class="dia">Jue</div>
                    <div class="dia">Vie</div>
                    <div class="dia">Sáb</div>
                    <div class="dia">Dom</div>
                </div>
                <div class="dias">
                    <div class="dia-mes"></div>
                    <div class="dia-mes"></div>
                    <div class="dia-mes"></div>
                    <div class="dia-mes"></div>
                    <div class="dia-mes">1</div>
                    <div class="dia-mes">2</div>
                    <div class="dia-mes">3</div>
                    <div class="dia-mes">4</div>
                    <div class="dia-mes">5</div>
                    <div class="dia-mes">6</div>
                    <div class="dia-mes">7</div>
                    <div class="dia-mes">8</div>
                    <div class="dia-mes">9</div>
                    <div class="dia-mes">10</div>
                    <div class="dia-mes">11</div>
                    <div class="dia-mes">12</div>
                    <div class="dia-mes">13</div>
                    <div class="dia-mes">14</div>
                    <div class="dia-mes">15</div>
                    <div class="dia-mes">16</div>
                    <div class="dia-mes">17</div>
                    <div class="dia-mes">18</div>
                    <div class="dia-mes">19</div>
                    <div class="dia-mes">20</div>
                    <div class="dia-mes">21</div>
                    <div class="dia-mes">22</div>
                    <div class="dia-mes">23</div>
                    <div class="dia-mes">24</div>
                    <div class="dia-mes">25</div>
                    <div class="dia-mes">26</div>
                    <div class="dia-mes">27</div>
                    <div class="dia-mes">28</div>
                    <div class="dia-mes">29</div>
                    <div class="dia-mes">30</div>
                    <div class="dia-mes">31</div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-5">
        <br />
        <div class="h3 fw-bold">Notificaciones</div>
        <br />
        <div class="card notificacion">

            <div class="card-body">
                <div class="card-title h5">Nuevo profesor registrado</div>
                <div class="card-text">Administrador Luis ha registrado al profesor Martín.</div>
            </div>

        </div>

        <br />
        <div class="card notificacion">
            <div class="card-body">
                <div class="card-title h5">Nueva materia registrada</div>
                <div class="card-text">Administrador Francisco ha registrado la materia "Probabilidad y estadística.</div>
            </div>
        </div>

        <br />
        <div class="card notificacion">
            <div class="card-body">
                <div class="card-title h5">Nuevo horario generado</div>
                <div class="card-text">Administrador Manuel generó horarios para el Ciclo Escolar 2024 - 2025.</div>
            </div>
        </div>
    </div>
</div>

<script>
    function actualizarReloj() {
        const ahora = new Date();

        const horas = ahora.getHours();
        const minutos = ahora.getMinutes();

        document.getElementById('hora').innerText = horas < 10 ? '0' + horas : horas;
        document.getElementById('minutos').innerText = minutos < 10 ? '0' + minutos : minutos;
    }

    // Actualiza el reloj cada segundo
    setInterval(actualizarReloj, 1000);

    // Llama a la función para que se actualice de inmediato
    actualizarReloj();

</script>

PanelGestorDeHorarios/Views/Superadministrador/PanelSuperadministrador.cshtml
@{
    ViewData["Title"] = "Panel Superadministrador";
}

<h1 class="text-center">Panel Superadministrador</h1>

<br />
<form asp-controller="" asp-action="" method="post">
	<div class="form-group">
		<div class="form-group row">
			<label for="Email" class="col-sm-4 col-form-label fw-bold">Email: </label>
			<div class="col-sm-8">
				<input type="text" name="Email" id="Email" class="form-control" />
			</div>
		</div>

		<br />
		<div class="form-group row">
			<label for="Rol" class="col-sm-4 col-form-label fw-bold">Rol: </label>
			<div class="col-sm-8">
				<select id="Rol" class="form-select">
					<option value="profesor1">Profesor</option>
					<option value="profesor2">Administrador</option>
				</select>
			</div>
		</div>

		<br />
		<div class="form-group row">
			<label for="Password" class="col-sm-4 col-form-label fw-bold">Contraseña: </label>
			<div class="col-sm-8">
				<input type="password" name="Password" id="Password" class="form-control" />
			</div>
		</div>

		<br />
		<br />
		<div class="text-center">
			<button type="submit" class="btn btn-custom">Registrar Usuario</button>
		</div>
	</div>
</form>

PanelGestorDeHorarios/Views/Superadministrador/PersonalizarPagina.cshtml
@{
	ViewData["Title"] = "Personalizar Pagina";
}

<h1 class="text-center">Personalizar Página</h1>

<form method="post" enctype="multipart/form-data" asp-controller="Logo" asp-action="Upload">
	<div class="form-group">
		<div>
			<label for="imageFile" class="fw-bold">Logotipo actual: &nbsp;</label>
			<img src="~/logo.png" height="50" width="50" alt="Imagen" />
			<br />
			<span class="fw-bold">Cambiar logotipo: </span>
			<input type="file" name="imageFile" id="imageFile" class="form-control" />
		</div>

		<br />
		<div>
			<label for="backgroundFile" class="fw-bold">Fondo actual: &nbsp;</label>
			<img src="~/background.jpg" height="50" width="100" alt="Imagen" />
			<br />
			<span class="fw-bold">Cambiar fondo: </span>
			<input type="file" name="backgroundFile" id="backgroundFile" class="form-control" />
		</div>

		<br />

		<div class="form-group row">
			<label for="color" class="col-sm-4 col-form-label fw-bold">Colores de la aplicación: </label>
			<div class="col-sm-8">
				<input type="text" name="color" id="color" class="form-control" />
			</div>
		</div>

		<br />

		<div class="form-group row">
			<label for="telefono" class="col-sm-4 col-form-label fw-bold">Teléfono: </label>
			<div class="col-sm-8">
				<input type="text" name="telefono" id="telefono" class="form-control" />
			</div>
		</div>

		<br />

		<div class="form-group row">
			<label for="direccion" class="col-sm-4 col-form-label fw-bold">Dirección: </label>
			<div class="col-sm-8">
				<input name="direccion" id="direccion" class="form-control" />
			</div>
		</div>

		<br />

		<div class="form-group row">
			<label for="correo" class="col-sm-4 col-form-label fw-bold">Correo: </label>
			<div class="col-sm-8">
				<input name="correo" id="correo" class="form-control" />
			</div>
		</div>

		<br />

		<div class="form-group row">
			<label for="redSocial1" class="col-sm-4 col-form-label fw-bold">Redes Social 1: </label>
			<div class="col-sm-8">
				<input name="redSocial1" id="redSocial1" class="form-control" />
			</div>
		</div>

		<br />

		<div class="form-group row">
			<label for="redSocial2" class="col-sm-4 col-form-label fw-bold">Redes Social 2: </label>
			<div class="col-sm-8">
				<input name="redSocial2" id="redSocial2" class="form-control" />
			</div>
		</div>

		<br />

		<div class="form-group row">
			<label for="redSocial3" class="col-sm-4 col-form-label fw-bold">Redes Social 3: </label>
			<div class="col-sm-8">
				<input name="redSocial3" id="redSocial3" class="form-control" />
			</div>
		</div>
	</div>

	<br />
	<div class="text-center">
		<button type="submit" class="btn btn-custom">Guardar cambios</button>
	</div>

</form>

PanelGestorDeHorarios/Views/Superadministrador/Soporte.cshtml
@{
    ViewData["Title"] = "Soporte";
}

<h1 class="text-center">Soporte Técnico</h1>

<h5 class="text-center">Utiliza este soporte para reportar quejas, sugerencias, dudas o errores de la aplicación. Un miembro del equipo de soporte responderá lo más pronto posible.</h5>

<br />
<form method="post" enctype="multipart/form-data" asp-controller="Logo" asp-action="Upload">
    <div class="form-group row">
        <label for="nombreCompleto" class="col-sm-4 col-form-label fw-bold">Nombre Completo: </label>
        <div class="col-sm-8">
            <input type="text" name="nombreCompleto" id="nombreCompleto" class="form-control" />
        </div>
    </div>

    <br />

    <div class="form-group row">
        <label for="asunto" class="col-sm-4 col-form-label fw-bold">Asunto: </label>
        <div class="col-sm-8">
            <input type="text" name="asunto" id="asunto" class="form-control" />
        </div>
    </div>

    <br />

    <div class="form-group row">
        <label for="email" class="col-sm-4 col-form-label fw-bold">Email: </label>
        <div class="col-sm-8">
            <input type="text" name="email" id="email" class="form-control" />
        </div>
    </div>

    <br />

    <div class="form-group row">
        <label for="descripcion" class="col-sm-4 col-form-label fw-bold">Descripción: </label>
		<div class="col-sm-8">
            <textarea type="text" name="descripcion" id="descripcion" rows="5" class="form-control"></textarea>
        </div>
    </div>

    <br />
    <div class="text-center">
        <button type="submit" class="btn btn-custom">Enviar reporte</button>
    </div>
</form>