PanelGestorDeHorarios/Controllers/AdministradorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OfficeOpenXml;
using System.IO;

namespace PanelGestorDeHorarios.Controllers
{
    public class AdministradorController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public AdministradorController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GenerarHorarios()
        {
            return View();
        }

        public IActionResult ConsultarHorarios()
        {
            return View();
        }

        public IActionResult ConsultarPerfilProfesor()
        {
            return View();
        }

		public IActionResult PanelAdministrador()
		{
			return View();
		}

        [HttpGet]
        public async Task<IActionResult> GenerarHorariosConsumir()
        {
            string apiURL = "https://oip33he60m.execute-api.us-east-2.amazonaws.com/horario/generado";
                
            using (HttpClient client = new())
            {
                try
                {
                    // Realizar una solicitud GET al endpoint de la API
                    HttpResponseMessage response = await client.GetAsync(apiURL);
                    Console.WriteLine(apiURL);

                    // Verificar si la solicitud fue exitosa
                    if (response.IsSuccessStatusCode)
                    {
                        // Leer el contenido de la respuesta como una cadena JSON
                        string responseBody = await response.Content.ReadAsStringAsync();

                        Console.WriteLine("Respuesta de la API:");
                        Console.WriteLine(responseBody);
                        TempData["StringHorarioGenerado"] = responseBody;

                        GenerateExcelFromJson("horarios.xlsx", responseBody);
                    }
                    else
                    {
                        Console.WriteLine($"La solicitud no fue exitosa. Código de estado: {response.StatusCode}");
                        TempData["ErrorAlGenerarHorario"] = "No se ha podido generar un horario. Intente de nuevo más tarde.";
                    }
                    return RedirectToAction("GenerarHorarios", "administrador");
                }
                catch (HttpRequestException ex)
                {
                    Console.WriteLine($"Error al realizar la solicitud HTTP: {ex.Message}");
                    TempData["ErrorAlGenerarHorario"] = "No se ha podido generar un horario. Intente de nuevo más tarde.";
                    return RedirectToAction("GenerarHorarios", "administrador");
                }
            }
        }

        public void GenerateExcelFromJson(string excelFilePath, string jsonText)
        {
            // Parsear el JSON a un objeto dinámico
            dynamic jsonData = JObject.Parse(jsonText);

            // Crear un nuevo archivo Excel
            using (ExcelPackage excelPackage = new ExcelPackage())
            {
                // Agregar una hoja al libro de trabajo
                ExcelWorksheet worksheet = excelPackage.Workbook.Worksheets.Add("Data");

                // Escribir los datos en el archivo Excel
                int rowIndex = 1;
                foreach (var item in jsonData)
                {
                    int colIndex = 1;
                    foreach (var prop in item)
                    {
                        worksheet.Cells[rowIndex, colIndex].Value = prop.ToString();
                        colIndex++;
                    }
                    rowIndex++;
                }

                // Guardar el archivo Excel en disco
                FileInfo excelFile = new FileInfo(excelFilePath);
                excelPackage.SaveAs(excelFile);
            }
        }

    }
}

PanelGestorDeHorarios/Views/Administrador/ConsultarHorarios.cshtml
@{
    ViewData["Title"] = "Consultar Horarios";
}

<h1 class="text-center">Consultar Horarios</h1>

<br />
<div class="form-group row">
    <label for="profesor" class="col-sm-4 col-form-label fw-bold">Seleccione profesor: </label>
    <div class="col-sm-8">
        <select id="profesor" class="form-select">
            <option value="profesor1">Profesor 1</option>
            <option value="profesor2">Profesor 2</option>
            <option value="profesor3">Profesor 3</option>
        </select>
    </div>
</div>

<br />
<br />
<div class="text-center">
    <button type="submit" class="btn btn-custom">Descargar Horarios</button>
</div>

PanelGestorDeHorarios/Views/Administrador/ConsultarPerfilProfesor.cshtml
@{
    ViewData["Title"] = "Consultar Perfil Profesor";
}

<h1 class="text-center">Consultar Perfil Profesor</h1>

<br />
<div class="form-group row">
    <label for="profesor" class="col-sm-4 col-form-label fw-bold">Seleccione profesor: </label>
    <div class="col-sm-8">
        <select id="profesor" class="form-select">
            <option value="profesor1">Profesor 1</option>
            <option value="profesor2">Profesor 2</option>
            <option value="profesor3">Profesor 3</option>
        </select>
    </div>
</div>

<br />
<br />
<div class="text-center">
    <button type="submit" class="btn btn-custom">Consultar Perfil</button>
</div>

PanelGestorDeHorarios/Views/Administrador/GenerarHorarios.cshtml
@{
    ViewData["Title"] = "Generar Horarios";
}

<h1 class="text-center">Generar Horarios</h1>

<br />
<form asp-controller="Administrador" asp-action="GenerarHorariosConsumir" method="get">
    <div class="text-center">
        <button type="submit" class="btn btn-custom">Generar Horarios</button>
    </div>
</form>

<br />
<br />
<div class="text-center">
    <button type="submit" class="btn btn-custom">Subir horarios</button>
</div>

@{
    var stringHorarioGenerado = @TempData["StringHorarioGenerado"];
    var errorAlGenerarHorario = @TempData["ErrorAlGenerarHorario"];

    if (stringHorarioGenerado != null)
    {
        <div class="fw-bold">Horario generado:</div>
        <div>@stringHorarioGenerado</div>
    }

    if (errorAlGenerarHorario != null)
    {
        <div class="fw-bold">Horario generado:</div>
        <div>@errorAlGenerarHorario</div>
    }
}

PanelGestorDeHorarios/Views/Administrador/Index.cshtml
@{
    ViewData["Title"] = "Vista de Administrador";
}

<h1 class="text-center">Vista de Administrador</h1>

PanelGestorDeHorarios/Views/Administrador/PanelAdministrador.cshtml
@{
    ViewData["Title"] = "Panel Administrador";
}

<h1 class="text-center">Panel Administrador</h1>

<br />
<form asp-controller="" asp-action="" method="post">
	<div class="form-group">
		<div class="form-group row">
			<label for="Email" class="col-sm-4 col-form-label fw-bold">Email: </label>
			<div class="col-sm-8">
				<input type="text" name="Email" id="Email" class="form-control" />
			</div>
		</div>

		<br />
		<div class="form-group row">
			<label for="Rol" class="col-sm-4 col-form-label fw-bold">Rol: </label>
			<div class="col-sm-8">
				<select id="Rol" class="form-select">
					<option value="profesor1">Profesor</option>
				</select>
			</div>
		</div>

		<br />
		<div class="form-group row">
			<label for="Password" class="col-sm-4 col-form-label fw-bold">Contraseña: </label>
			<div class="col-sm-8">
				<input type="password" name="Password" id="Password" class="form-control" />
			</div>
		</div>

		<br />
		<br />
		<div class="text-center">
			<button type="submit" class="btn btn-custom">Registrar Usuario</button>
		</div>
	</div>
</form>