PanelGestorDeHorarios/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using PanelGestorDeHorarios.Models;
using System.Text.Json;

namespace PanelGestorDeHorarios.Controllers
{
    public class RolesController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> Login(Usuario datosLogin)
        {
            Console.WriteLine(datosLogin.folio);
            Console.WriteLine(datosLogin.password);

            string rol = "";
            string baseUrl = "https://d5stm6fym6.execute-api.us-east-2.amazonaws.com/login/usuario";
            string queryString = $"?folio={datosLogin.folio}&password={datosLogin.password}";

            // Crear una instancia de HttpClient
            using (HttpClient client = new())
            {
                try
                {
                    // Realizar una solicitud GET al endpoint de la API
                    HttpResponseMessage response = await client.GetAsync(baseUrl + queryString);
                    Console.WriteLine(baseUrl + queryString);

                    // Verificar si la solicitud fue exitosa
                    if (response.IsSuccessStatusCode)
                    {
                        // Leer el contenido de la respuesta como una cadena JSON
                        string responseBody = await response.Content.ReadAsStringAsync();

                        Console.WriteLine("Respuesta de la API:");
                        Console.WriteLine(responseBody);

                        // Crear root, que es una representación del JSON en un objeto de C#
                        var doc = JsonDocument.Parse(responseBody);
                        var root = doc.RootElement;

                        var folio = root.GetProperty("folio").GetString();
                        rol = root.GetProperty("rol").GetString() ?? "";
                        Console.WriteLine($"{folio} {rol}");

                        //    Console.WriteLine($"{folio} {rol}");
                        //// Como se garantiza que la respuesta de esta API es un Array JSON, entonces se recorre cada objeto de ese array.
                        //foreach (var user in root.EnumerateArray())
                        //{
                        //    var folio = user.GetProperty("folio").GetString();
                        //    rol = user.GetProperty("rol").GetString();
                        //    Console.WriteLine($"{folio} {rol}");
                        //}
                    }
                    else
                    {
                        Console.WriteLine($"La solicitud no fue exitosa. Código de estado: {response.StatusCode}");
                    }
                }
                catch (HttpRequestException ex)
                {
                    Console.WriteLine($"Error al realizar la solicitud HTTP: {ex.Message}");
                }
            }

            // Si encuentra un usuario y contraseña válidos en un mismo registro, entonces se crea una cookie de autenticación en la aplicación.
            if (rol != "")
            {
                // Se crea una lista de propiedades (Claims) para la autenticación. En este caso, se toma el nombre del usuario del formulario y se le asignan roles. Los roles servirán para saber qué páginas puede o no visitar el usuario.
                var claims = new List<Claim> {
                    // new(ClaimTypes.Name, autenticacion.id_usuario.ToString()),
                    new(ClaimTypes.Name, "Alan"),
                    // new(ClaimTypes.Role, autenticacion.id_rol.ToString()) // Se puede asignar una lista de roles al usuario autenticado si se toman de una BD.
                    new(ClaimTypes.Role, rol ?? "")
                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                // Autenticar al usuario con los Claims especificados.
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                return RedirectToAction("RedireccionarSegunRol", "AsignarVista");
            }
            else
            { // De no haber ingresado un usuario y contraseña válidos, recargará la página, mostrando un mensaje de que has introducido un usuario o contraseña inválidos.
                TempData["MensajeDeErrorLogin"] = "Usuario o contraseña inválidos. Intente de nuevo"; // TempData persiste una redirección, cosa que ni ViewBag ni ViewData pueden hacer.
                return RedirectToAction("Login", "Home");
            }
        }

        public async Task<IActionResult> LoginSuper(Usuario autenticacion)
        {
            string rol = "superadministrador";

            // Si encuentra un usuario y contraseña válidos en un mismo registro, entonces se crea una cookie de autenticación en la aplicación.
            if (true)
            {
                // Se crea una lista de propiedades (Claims) para la autenticación. En este caso, se toma el nombre del usuario del formulario y se le asignan roles. Los roles servirán para saber qué páginas puede o no visitar el usuario.
                var claims = new List<Claim> {
                    // new(ClaimTypes.Name, autenticacion.id_usuario.ToString()),
                    new(ClaimTypes.Name, "Alan"),
                    // new(ClaimTypes.Role, autenticacion.id_rol.ToString()) // Se puede asignar una lista de roles al usuario autenticado si se toman de una BD.
                    new(ClaimTypes.Role, rol)
                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                // Autenticar al usuario con los Claims especificados.
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                return RedirectToAction("RedireccionarSegunRol", "AsignarVista");
            }
            else
            { // De no haber ingresado un usuario y contraseña válidos, recargará la página, mostrando un mensaje de que has introducido un usuario o contraseña inválidos.
                TempData["MensajeDeErrorLogin"] = "Usuario o contraseña inválidos. Intente de nuevo"; // TempData persiste una redirección, cosa que ni ViewBag ni ViewData pueden hacer.
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> LoginAdmin(Usuario autenticacion)
        {
            string rol = "administrador";

            // Si encuentra un usuario y contraseña válidos en un mismo registro, entonces se crea una cookie de autenticación en la aplicación.
            if (true)
            {
                // Se crea una lista de propiedades (Claims) para la autenticación. En este caso, se toma el nombre del usuario del formulario y se le asignan roles. Los roles servirán para saber qué páginas puede o no visitar el usuario.
                var claims = new List<Claim> {
                    // new(ClaimTypes.Name, autenticacion.id_usuario.ToString()),
                    new(ClaimTypes.Name, "Alan"),
                    // new(ClaimTypes.Role, autenticacion.id_rol.ToString()) // Se puede asignar una lista de roles al usuario autenticado si se toman de una BD.
                    new(ClaimTypes.Role, rol)
                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                // Autenticar al usuario con los Claims especificados.
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                return RedirectToAction("RedireccionarSegunRol", "AsignarVista");
            }
            else
            { // De no haber ingresado un usuario y contraseña válidos, recargará la página, mostrando un mensaje de que has introducido un usuario o contraseña inválidos.
                TempData["MensajeDeErrorLogin"] = "Usuario o contraseña inválidos. Intente de nuevo"; // TempData persiste una redirección, cosa que ni ViewBag ni ViewData pueden hacer.
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> LoginProfesor(Usuario autenticacion)
        {
            string rol = "profesor";

            // Si encuentra un usuario y contraseña válidos en un mismo registro, entonces se crea una cookie de autenticación en la aplicación.
            if (true)
            {
                // Se crea una lista de propiedades (Claims) para la autenticación. En este caso, se toma el nombre del usuario del formulario y se le asignan roles. Los roles servirán para saber qué páginas puede o no visitar el usuario.
                var claims = new List<Claim> {
                    // new(ClaimTypes.Name, autenticacion.id_usuario.ToString()),
                    new(ClaimTypes.Name, "Alan"),
                    // new(ClaimTypes.Role, autenticacion.id_rol.ToString()) // Se puede asignar una lista de roles al usuario autenticado si se toman de una BD.
                    new(ClaimTypes.Role, rol)
                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                // Autenticar al usuario con los Claims especificados.
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                return RedirectToAction("RedireccionarSegunRol", "AsignarVista");
            }
            else
            { // De no haber ingresado un usuario y contraseña válidos, recargará la página, mostrando un mensaje de que has introducido un usuario o contraseña inválidos.

PanelGestorDeHorarios/Controllers/SharedController.cs
using Microsoft.AspNetCore.Mvc;

namespace PanelGestorDeHorarios.Controllers
{
    public class SharedController : Controller
    {
        public IActionResult AccesoDenegado()
        {
            return View();
        }
    }
}

PanelGestorDeHorarios/Views/Shared/AccesoDenegado.cshtml
@{
    ViewData["Title"] = "AccesoDenegado";
}

<br />
<h1 class="text-danger">Acceso denegado :(</h1>
<h2 class="text-danger">Usted no tiene acceso a esta página.</h2>
<h3 class="text-danger">Póngase en contacto con el administrador si considera que esto es un error.</h3>

PanelGestorDeHorarios/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PanelGestorDeHorarios</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PanelGestorDeHorarios.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="background"></div>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img src="~/logo.png" height="50" width="50" alt="Logo" />
                @* <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Login">
                    <img src="~/logo.png" height="50" width="50" alt="Logo" />
                </a> *@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @{
                            #pragma warning disable CS8602 // Desreferencia de una referencia posiblemente NULL.
                            // Si el usuario está autenticado, se le presentará en la Navbar un botón de cerrar sesión.
                            if (User.IsInRole("superadministrador"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="superadministrador" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="superadministrador" asp-action="PersonalizarPagina">Personalizar página</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="superadministrador" asp-action="Soporte">Soporte</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="superadministrador" asp-action="PanelSuperadministrador">Panel Super Administrador</a>
                                </li>
                            }
                            #pragma warning restore CS8602 // Desreferencia de una referencia posiblemente NULL.
                        }
                        @{
                            #pragma warning disable CS8602 // Desreferencia de una referencia posiblemente NULL.
                            // Si el usuario está autenticado, se le presentará en la Navbar un botón de cerrar sesión.
                            if (User.IsInRole("administrador") || User.IsInRole("superadministrador"))
                            {
                                if (!User.IsInRole("superadministrador"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="administrador" asp-action="Index">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="administrador" asp-action="PanelAdministrador">Panel Administrador</a>
                                    </li>
                                }

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="administrador" asp-action="GenerarHorarios">Generar Horarios</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="administrador" asp-action="ConsultarHorarios">Consultar Horarios</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="administrador" asp-action="ConsultarPerfilProfesor">Consultar Perfil Profesor</a>
                                </li>
                            }
                            #pragma warning restore CS8602 // Desreferencia de una referencia posiblemente NULL.
                        }
                        @{
                        #pragma warning disable CS8602 // Desreferencia de una referencia posiblemente NULL.
                            // Si el usuario está autenticado, se le presentará en la Navbar un botón de cerrar sesión.
                            if (User.IsInRole("profesor"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="profesor" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="profesor" asp-action="Perfil">Mi Perfil</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="profesor" asp-action="MiHorario">Mi Horario</a>
                                </li>
                            }
                        #pragma warning restore CS8602 // Desreferencia de una referencia posiblemente NULL.
                        }
                        @{
                            #pragma warning disable CS8602 // Desreferencia de una referencia posiblemente NULL.
                            // Si el usuario está autenticado, se le presentará en la Navbar un botón de cerrar sesión.
                            if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Logout">Cerrar sesión</a>
                                </li>
                            } else
                            {
                                // Si el usuario está autenticado, se le presentará en la Navbar un botón de cerrar sesión.
                                if (!User.Identity.IsAuthenticated)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Iniciar sesión</a>
                                    </li>
                                }
                            }
                            #pragma warning restore CS8602 // Desreferencia de una referencia posiblemente NULL.
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted container-fluid row">
        <div class="container col-md-1">.</div>
        <div class="container col-md-5">
            <div class="h4 mt-3">Contacto</div>
            <div><span class="fw-bold">Teléfono: &nbsp;</span><span>999-123-4567</span></div>
            <div><span class="fw-bold">Correo: &nbsp</span><span>Ejemplo@@itmerida.com.mx</span></div>
            <div><span class="fw-bold">Dirección: &nbsp;</span><span>Av. Tecnológico S/N Km. 4.5 C.P. 97118, Mérida Yuc.</span></div>
        </div>
        <div class="container col-md-1">.</div>
        <div class="container col-md-4">
            <span class="h4">Redes: &nbsp;</span>
            <a href=""><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/2023_Facebook_icon.svg/2048px-2023_Facebook_icon.svg.png" alt="RedSocial1.png" width="20", height="20"/></a>
            <a href=""><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/X_icon_2.svg/2048px-X_icon_2.svg.png" alt="RedSocial1.png" width="20" , height="20" /></a>
            <a href=""><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/1200px-Instagram_icon.png" alt="RedSocial1.png" width="20" , height="20" /></a>
            <div>
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14898.0199824681!2d-89.6221622!3d21.0124706!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8f5676a65077d641%3A0x39dfe74777312656!2sTecNM%20-%20Campus%20M%C3%A9rida!5e0!3m2!1ses-419!2smx!4v1710591006325!5m2!1ses-419!2smx" width="300" height="200" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
        <div class="container col-md-1">.</div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>